### ISSUE TITLE
umi generate tmp时候失败

### ISSUE THREAD

**Issue by zhu110guang** [duan602728596/umi-plugin-redux-toolkit#3]
![image](https://user-images.githubusercontent.com/18319392/177256285-d7210de5-b7a3-4b42-8b27-b4d718304de4.png)

当我使用最新版本的umi 安装本插件时, 安装完了以后在umi generate tmp 阶段会报如下错误:

Cannot read property 'key' of undefined
TypeError: Cannot read property 'key' of undefined
    at Object.fn (D:\work\umi-test\node_modules\umi-plugin-redux-toolkit\dist\plugin\index.js:10:41)
    at D:\work\umi-test\node_modules\@umijs\core\lib\Service\Service.js:549:44
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\work\umi-test\node_modules\@umijs\core\lib\Service\Service.js:110:103)
    at _next (D:\work\umi-test\node_modules\@umijs\core\lib\Service\Service.js:112:194)
    at D:\work\umi-test\node_modules\@umijs\core\lib\Service\Service.js:112:364
    at new Promise (<anonymous>)
    at D:\work\umi-test\node_modules\@umijs\core\lib\Service\Service.js:112:97
    at D:\work\umi-test\node_modules\@umijs\core\lib\Service\Service.js:554:31
    at _next3 (eval at create (D:\work\umi-test\node_modules\@umijs\deps\compiled\tapable\index.js:1:7845), <anonymous>:17:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by duan602728596** [comment]
确实有个问题，我会调试一下

**Comment by duan602728596** [comment]
你必须手动注册插件
https://umijs.org/docs/guides/plugins#%E5%90%AF%E7%94%A8%E6%8F%92%E4%BB%B6
